baseURL: https://example.org/
languageCode: en-us
title: Chen'Log


module:
  imports:
  - path: github.com/adityatelange/hugo-PaperMod

theme: ["PaperMod"]

params:
  homeInfoParams:
    Title: "👋 Welcome to Chen'Log"
    Content: Hello, this is Jonathan. I'm using a blog to keep track of my learning notes throughout my career. I find most fields in software development quite fascinating, however I am probably going to specialize in backend, database/cloud, system design, and possibly machine learning.
  socialIcons:
    - name:   github
      url: "https://github.com/jonathanc-n"
    - name: linkedin
      url: "https://www.linkedin.com/in/jonathan-chen-5218b3253/"
  ShowBreadCrumbs: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true

menu:
  main:
    - identifier: categories
      name: Categories
      url: /categories/
      weight: 10
    - identifier: tags
      name: Tags
      url: /Tags/
      weight: 20
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 30